name: Deployment workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    name: Checkoout the branch, install dependencies, and run tests
    runs-on: ubuntu-22.04
    steps:
      # Use an external action
      - uses: actions/checkout@v3
        # Attributes we want to use to execute the action
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install dependencies
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      # Run tests
      - name: Run tests
        run: npm run test
      # Deploy to Render
      - name: Deploy to Render
        if: ${{ github.event_name == 'push' }}
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false #optional, default true
      - name: Log github event
        run: echo ${{ github.event_name }}
        